### ISSUE TITLE
Fix Homepage input 

### ISSUE THREAD

**Issue by Timi-Leyin** [linkashare/linkashare-ui#15]
- redesign the form as one provided in the design
- ## Current design 
![Screenshot_20220914-001539~2](https://user-images.githubusercontent.com/67488936/190026452-f62763b2-a362-4448-b361-15fe375c1bec.png)
## Expected design 
![Screenshot_20220914-001828~3](https://user-images.githubusercontent.com/67488936/190026479-92cf9392-9b31-45c7-9e5d-8f7576382812.png)

**Comment by dev-phantom** [comment]
.take
